# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
                ('url_tag_name', models.SlugField(editable=False)),
                ('post', models.CharField(max_length=1000)),
                ('tag_name_length', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
